services:
  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: ultimate_auth_backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    container_name: ultimate_auth_frontend
    ports:
      - "3000:3000"  # Match the port exposed by Nginx
    depends_on:
      - backend
