services:
  db:
    image: postgres
    container_name: ultimate_auth_db
    environment:
      POSTGRES_DB: ultimate_auth
      POSTGRES_USER: ahmed
      POSTGRES_PASSWORD: ultimate_auth_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ultimate_auth_backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      PGHOST: db
      POSTGRES_DB: ultimate_auth
      POSTGRES_USER: ahmed
      POSTGRES_PASSWORD: ultimate_auth_password

    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "
        python3 manage.py migrate --noinput &&
        gunicorn --bind 0.0.0.0:8000 ultimate_auth.wsgi:application
      "



volumes:
  pgdata:
