services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ultimate_auth_backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "
        python3 manage.py migrate --noinput &&
        gunicorn --bind 0.0.0.0:8000 ultimate_auth.wsgi:application
      "

  db:
    image: postgres
    container_name: ultimate_auth_db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    # ⚠️ No "ports:" here! Keep DB internal-only.

volumes:
  pgdata:
